# .github/workflows/release.yml
  name: Release

  on:
    push:
      tags: ['v*']

  jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}

      steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu  # for Windows builds

      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: pomo-${{ matrix.os }}
          path: target/release/pomo*
